### ISSUE TITLE
Crashes when built from source; missing armors directory

### ISSUE THREAD

**Issue by gmstriga** [itytophile/rab#1]
This is easy enough to work around by copying the directory from the release, but I'm left wondering why it's in the .gitignore in the first place. I'm of the opinion that data like that is part of the tool and should live in source control along with the source code.

**Comment by gmstriga** [comment]
Disregard, I did the exact thing I get annoyed at my coworkers for doing and ignored the part in the readme where it says the armor files are already in git in another repo.

**Comment by itytophile** [comment]
In the next version, I'll display a message on the window to tell what to do if the folder is missing. In any case, thanks for trying RAB!
